apiVersion: v1
kind: Service
metadata:
  name: mongo-nodeport-svc
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    nodePort: 32000
